### ISSUE TITLE
Add PVLive sum of GSPs

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/uk-analysis-dashboard#27]
It would be really useful to add PVLive sum of GSPs as an alternative option to the PVLive national estimate

## Context

- @JackKelly had mentioned that PVLive sum of GSPs is likely a better estimate of the true output than the PVLive national estimate. However, the national estimate is what everyone else uses, so I don't think a straight replacement would be the best thing to do. Maybe have both.
- PVNet 1 and 2 produce a national estimate by predicting the GSP values and then summing them. To help monitor the performance of those models, it would be good to have the PVLive sum of GSPs - the PVNet sum is likely to be more similar to this. This could help us asses whether the model is getting the forecast wrong, or if the potential errors in the PVNet national forecast is due to the difference between the PVLive national and PVLive sum of GSPs.

## Possible Implementation

- As a user, I'd love to be able to see the PVLive sum of GSPs when looking at national, and maybe see both PVLive options and our predictions on the same graph on the forecast tab. Maybe it could be done in the same kind of way that we select the models ncluded, which defaults just to the cnn?
- If possible, it would be great to optionally show the the MAE metrics computed with respect to the PVLive sum of GSPs. Maybe just a toggle which to compare to?

**Comment by peterdudfield** [comment]
@rachel-labri-tipton I could help you write some SQL that would pull the sum of GSP rather than pulling each GSP from the database and then summing. You  could then do the changes, adding the toggle, in this dashboard?

**Comment by rachel-labri-tipton** [comment]
thanks! @peterdudfield. sounds great!
