### ISSUE TITLE
site forecast page

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-analysis-dashboard#41]
## Detailed Description
Add a page that can see the site forecasts

## Context
- good to be able to select one or mulitle sites and see the forecast
- similar issue to forecast page for gsp and national

## Possible Implementation
- drop down menu to select a site
- options on start and end date
- see truths (if there are any)
- see forecasts

**Comment by peterdudfield** [comment]
get all sites - https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/read/site.py#L82

read function for generation - https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/read/generation.py#L66

read function for forecast - https://github.com/openclimatefix/pv-site-datamodel/blob/main/pvsite_datamodel/read/latest_forecast_values.py#L11

**Comment by rachel-labri-tipton** [comment]
hi @peterdudfield, I’m working on getting the `site_uuids` from the database . When I call `get_all_sites` , I’m having trouble converting the data to a list of `site_uuids` and keep getting the error: `AttributeError: type object 'SiteSQL' has no attribute 'from_orm'`. 
Would adding a `def to_orm` function to the `SiteSQL` class in the the `pvsite_datamodel` fix this issue? Thanks!
