### ISSUE TITLE
Forecast page "Creation time" and "Forecast horizon" bug

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/uk-analysis-dashboard#43]
The streamlit app running on dev is erroring out on the forecast page when the selected forecast type is "Creation time" or "Forecast horizon". Error message is:

```
File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
File "/app/main.py", line 455, in <module>
    page_names_to_funcs[demo_name]()
File "/app/forecast.py", line 245, in forecast_page
    raise e
File "/app/forecast.py", line 215, in forecast_page
    properties_0 = forecast[0]._properties
```

It was working previously, and it still works on production. I'm not sure if it could be to do with PVNet2 being updated to be probabilistic on dev?

**Comment by rachel-labri-tipton** [comment]
thanks for flagging this, @dfulu! i think it is related to PVNet2 being updated to be probabilistic on dev. 

it looks like the error appears only if the `cnn` model is selected (at least for me deselecting that model removed the error). i realize this isn't a fix, but maybe in the short term you can try deselecting the cnn model if you want to see the `pvnet_v2` and `National_XG` forecasts?

i was able to get it working again locally by adding a line of code that doesn't look for probabilistic properties for the `cnn` model we should have it fixed soon.

**Comment by dfulu** [comment]
Great tip! Thanks for looking into this!

**Comment by peterdudfield** [comment]
This still a bug @dfulu @rachel-labri-tipton ?

**Comment by rachel-labri-tipton** [comment]
hi @peterdudfield, this has been resolved. i'll go ahead and close the issue.
