### ISSUE TITLE
analysis dashboard pv site forecast  page suggestions / feedback

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/uk-analysis-dashboard#48]
## Detailed Description

This issue is to collect feedback and ideas on the `PV Site Forecast` page recently deployed on the [Development Analysis Dashboard](http://nowcasting-development-internal-ui.eu-west-1.elasticbeanstalk.com/ ).

The page currently looks like this:
![Screenshot 2023-08-25 at 17 35 51](https://github.com/openclimatefix/uk-analysis-dashboard/assets/86949265/cd440589-7324-4f93-974d-6b91561ffa30)

For the moment, it's fairly basic. 
The original issue, #41 , was to plot forecast and generation (if data exists) values for a single pv site. 

A user can select a site by `site_uuid` (the unique id used in the database to differentiate sites) and choose a start date for the forecast and generation data. 
PV Site Forecast data currently only has 3-4 days of history, so the date selection doesn't go back any further than that for the moment. Some sites have generation data (displayed in orange), but many don't. 

What other information about the individual site page could be helpful?

Feel free to comment below what features or parameters could be helpful to add to this page. Ex. Lat / long coordinates, site generation capacity, etc.

**Comment by peterdudfield** [comment]
Shall we close this, as there is no feedback?
