### ISSUE TITLE
UI suggestions for sites toolbox 

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/uk-analysis-dashboard#71]
## Detailed Description
These are ideas for tidying up the sites toolbox UI

- In a user's site list, show the client_site_id before site_uuid
- Change label for date on `site` information. This refers to `created_utc`, which is in the datamodel => `date_added_to_ocf_db` would be better
 - Grouping of functions => organize functions so they're still modular but perhaps grouped together by color or style
- Add some documentation of users and site groups, how multiple relationships work, link to github

## Context
Sites Toolbox UI on the OCF dashboard could be improved by these changes to look a bit tidier and be easier to use. 

## Possible Implementation
Make changes to the UI in the `scr/sites_toolbox.py` file.

**Comment by peterdudfield** [comment]
Thanks @rachel-labri-tipton for putting these up here
