### ISSUE TITLE
wide plots

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/uk-analysis-dashboard#76]
st.set_page_config(layout="wide")

add this text (once) before plots to make all plots wide

**Comment by suleman1412** [comment]
hi I would like to work on this, only thing is I'm struggling to set up the repo on my local as I don't have access to forecast development database.

**Comment by peterdudfield** [comment]
> hi I would like to work on this, only thing is I'm struggling to set up the repo on my local as I don't have access to forecast development database.

Yea, im really sorry, we can give you that acess. You would have to set up your own ones. 

Perhaps with this one, its just a general streamlet option that can be added?

**Comment by suleman1412** [comment]
Hi @peterdudfield I have made the necessary changes, could you please take a look and let me know if the changes are satisfactory?
