### ISSUE TITLE
OCF Dashboard Sites Toolbox on Production

### ISSUE THREAD

**Issue by rachel-labri-tipton** [openclimatefix/uk-analysis-dashboard#87]

**Comment by peterdudfield** [comment]
Low priorty

I like the drop down menus. The last 6 have them. Would be great to add them to the others

![Screenshot 2023-10-16 at 09 34 27](https://github.com/openclimatefix/uk-analysis-dashboard/assets/34686298/679888c7-897a-494c-a256-c7491e303c5b)

**Comment by peterdudfield** [comment]
Could we make the actions into 2 columns, then we could get more on the page. Perhaps keep Delete ones near the bottoms for safety

**Comment by rachel-labri-tipton** [comment]
Great idea @peterdudfield. Columns would use the space more efficiently.

**Comment by peterdudfield** [comment]
> Great idea @peterdudfield. Columns would use the space more efficiently.

Would be nice if you have a small window, it drops down to one column

**Comment by peterdudfield** [comment]
I'll close this for the monent
